In [3]:
import numpy as np
import sys
import simpy

In [12]:
class Node:
    def __init__(self, env, name):
        self.env = env
        self.name = name
        self.addr = name
        self.links_in = []
        self.links_out = []
        self.output_port = []
        self.routing_table = {}
        
class Switch(Node):
    def __init__(self, env, name):
        super().__init__(env, name)
        
class Host(Node):
    def __init__(self, env, name, applications=None):
        super().__init__(env, name)
        self.applications = applications if applications is not None else []
        self.queue = simpy.Store(env)
        self.delay_dict = {}

In [13]:
env = simpy.Environment()
print(env)
node1 = Host(env, 1)
node2 = Host(env, 2)
node3 = Switch(env, 3)
node4 = Switch(env, 4)

In [14]:
class Topology:
    def __init__(self, env):
        self.env = env
        #self.topology_table = topology_table
        self.nodes = {}
        self.links = {}

In [27]:
topo = Topology(env)

if node1 not in topo.nodes:
    topo.nodes.update({node1 : node1})
    topo.links.update({node1 : {}})
    
if node2 not in topo.nodes:
    topo.nodes.update({node2 : node2})
    topo.links.update({node2 : {}})
    
if node3 not in topo.nodes:
    topo.nodes.update({node3 : node3})
    topo.links.update({node3 : {}})
    
if node4 not in topo.nodes:
    topo.nodes.update({node4 : node4})
    topo.links.update({node4 : {}})

In [29]:
print(topo.nodes)

{<__main__.Host object at 0x0000021ADB6EA190>: <__main__.Host object at 0x0000021ADB6EA190>, <__main__.Host object at 0x0000021ADB3684C0>: <__main__.Host object at 0x0000021ADB3684C0>, <__main__.Switch object at 0x0000021ADB368730>: <__main__.Switch object at 0x0000021ADB368730>, <__main__.Switch object at 0x0000021ADB368E20>: <__main__.Switch object at 0x0000021ADB368E20>}


In [28]:
print(topo.nodes[node1])

In [17]:
print(topo.nodes.keys())

dict_keys([<__main__.Host object at 0x0000021ADB6EA190>])


In [23]:
print(topo.nodes.values())

dict_values([<__main__.Host object at 0x0000021ADB6EA190>])


In [25]:
print(topo.links)

{<__main__.Host object at 0x0000021ADB6EA190>: {}}


In [22]:
print(topo.links.keys())

dict_keys([<__main__.Host object at 0x0000021ADB6EA190>])


In [26]:
print(topo.links.values())

dict_values([{}])


In [9]:
class Link(simpy.Store):
    #링크
    #필요 변수: 용량(capacity, bps단위), 물리적 거리(m단위)
    def __init__(self, env, link_capacity=100000000, distance=10):
        super().__init__(env)
        self.link_capacity = link_capacity
        self.distance = distance

In [10]:
def add_link(node10, node20):
    if node10 not in topo.nodes:
        topo.nodes.update({node10 : node10})
        topo.links.update({node10 : {}})
    if node20 not in topo.nodes:
        topo.nodes.update({node20 : node20})
        topo.links.update({node20 : {}})
    if node20 not in topo.links[node10]:
        link1 = Link(env)
        link2 = Link(env)
        topo.links[node10][node20] = link1
        topo.links[node20][node10] = link2
        topo.nodes[node10].add_link(link1, link2)
        topo.nodes[node20].add_link(link2, link1)

In [11]:
add_link(node1, node3)
add_link(node3, node4)
add_link(node4, node2)

AttributeError: 'Host' object has no attribute 'add_link'

In [ ]:
print(topo.links.values())

dict_values([{<__main__.Host object at 0x000002C1ECB7D540>: <__main__.Link object at 0x000002C1EE6BD810>}, {<__main__.Switch object at 0x000002C1EE611840>: <__main__.Link object at 0x000002C1EE6BCB80>}])


In [ ]:
for i in topo.links.values():
    for j in i.values():
        print(j.distance)

10
10


In [ ]:
distances = {node: sys.maxsize for node in topo.nodes.keys()}
routes = {node: sys.maxsize for node in topo.nodes.keys()}
distances[node1] = 0
routes[node1] = node1
queue = []

    ##여기에 코드 추가
queue = [node for node in topo.nodes.keys()]
#while(queue != None):
u = min(distances, key=lambda x: distances[x])
    #queue.remove(u)
print(u)
print(queue)
print(distances)
    #for neighbor in topo.nodes[u]:
    #    temp = distances[u] + topo.links[u][neighbor]
    #    if temp < distances[neighbor]:
    #        distances[neighbor] = temp
    #        routes[neighbor] = u 

[<__main__.Switch object at 0x000002C1EE611840>, <__main__.Host object at 0x000002C1ECB7D540>]
{<__main__.Switch object at 0x000002C1EE611840>: 0, <__main__.Host object at 0x000002C1ECB7D540>: 9223372036854775807}


In [1]:
import simpy

In [2]:
env = simpy.Environment()

In [3]:
import pandas as pd

flow_prd_list = [2, 4, 8, 16, 32, 64]

data = {
    'host1' : [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    'switch1' : [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    'switch2' : [1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
    'switch3' : [0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
    'switch4' : [0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
    'switch5' : [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
    'switch6' : [0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
    'switch7' : [0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
    'switch8' : [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
    'host2' : [0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
        }
    
index_name = data.keys()
df = pd.DataFrame(data, index=index_name)
print(df)

         host1  switch1  switch2  switch3  switch4  switch5  switch6  switch7  \
host1        0        1        1        0        0        0        0        0   
switch1      1        0        1        1        0        0        0        0   
switch2      1        1        0        0        1        0        0        0   
switch3      0        1        0        0        1        1        0        0   
switch4      0        0        1        1        0        0        1        0   
switch5      0        0        0        1        0        0        1        1   
switch6      0        0        0        0        1        1        0        0   
switch7      0        0        0        0        0        1        0        0   
switch8      0        0        0        0        0        0        1        1   
host2        0        0        0        0        0        0        0        1   

         switch8  host2  
host1          0      0  
switch1        0      0  
switch2        0      0  
swit

In [11]:

import random

prd = random.choice(flow_prd_list)
print(prd)

8


In [12]:
import numpy as np

slot_scheduler = np.zeros([1024, 4])

In [14]:
for idx, val in enumerate(slot_scheduler):
        if not any(val):#플로우가 할당이 되어있는지 확인
            print(val)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0.